spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zhangdx_blog?serverTimezone=Asia/Shanghai
    username: root
    password: 7102
  redis:
    host: 8.129.0.113
    password: 7102
    database: 1